<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<ProjectReference Include="../Leva.Framework.Core/Leva.Framework.Core.csproj" />
		<ProjectReference Include="../Leva.Framework.Engine/Leva.Framework.Engine.csproj" />
		<ProjectReference Include="../Leva.Framework.Identity/Leva.Framework.Identity.csproj" />
	</ItemGroup>
</Project>
