<Project Sdk="Microsoft.NET.Sdk.Web">
	<ItemGroup>
		<ProjectReference Include="../../src/Leva.Framework.Core/Leva.Framework.Core.csproj" />
		<ProjectReference Include="../../src/Leva.Framework.Notifications/Leva.Framework.Notifications.csproj" />
		<ProjectReference Include="../../src/Leva.Framework.Notifications.Memory/Leva.Framework.Notifications.Memory.csproj" />
		<ProjectReference Include="../../src/Leva.Framework.Notifications.SignalR/Leva.Framework.Notifications.SignalR.csproj" />
	</ItemGroup>
</Project>
